name: Test
run-name: ${{ github.actor }} running tests
on: [push]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.10
        uses: https://github.com/actions/setup-python@v1
        with:
          python-version: 3.10
      - name: Check out repository code
        uses: actions/checkout@v3
      # - name: Install Python and pip
      #   run: |
      #     apt update
      #     apt install -y python3-pip
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Run tests
        run: python -m unittest
