name: Test
run-name: ${{ github.actor }} running tests
on: [push]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Python and pip
        run: |
          apt update
          apt install python3-pip
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Run tests
        run: python -m unittest
